// The wasm package is generated by wasm-pack into ./pkg (see the build steps in
// the README). It is imported statically so Vite resolves the glue and serves
// the .wasm asset itself; the web build therefore requires the package to exist
// (build the wasm before the web app, as CI and run.sh do).
import init, { trace_wasm } from "./pkg/img2svg_core.js";

/** The stats shape the Rust core serializes (snake_case, palette as hex). */
export interface CoreStats {
  path_count: number;
  palette: string[];
  classified_as: string;
  est_bytes: number;
}

export interface CoreResult {
  svg: string;
  stats: CoreStats;
}

let ready: Promise<void> | null = null;

function ensureReady(): Promise<void> {
  if (!ready) {
    ready = init().then(() => undefined);
  }
  return ready;
}

/** Trace already-decoded RGBA. `coreOptions` must match the Rust `Options`. */
export async function traceRaw(
  rgba: Uint8Array,
  width: number,
  height: number,
  coreOptions: Record<string, unknown>,
): Promise<CoreResult> {
  await ensureReady();
  const json = trace_wasm(rgba, width, height, JSON.stringify(coreOptions));
  return JSON.parse(json) as CoreResult;
}
